name: LineageOS
on:
  push:
    branches:
      - cm-14.1
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 2
      - name: run docker container
        uses: docker://jakesoso/cm_build:los14.1
        with:
          args: /bin/bash -c "bash build.sh"

